tagFormat: 'v${version}'
branches:
  - 'main'

plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - - '@semantic-release/release-notes-generator'
    - preset: conventionalcommits
  - '@semantic-release/changelog'
  - - '@semantic-release/exec'
    - publishCmd: |
        export CI_COMMIT_TAG="true"
        sbt ci-release
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
  - '@semantic-release/github'