name: Build test and deploy
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
      name: Build and Test
      strategy:
        matrix:
          os: [ubuntu-22.04]
          scala: [2.13.2]
          java: [20.0.1]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout current branch
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Setup Scala
          uses: actions/setup-java@v3.5.0
          with:
            distribution: 'temurin'
            java-version: ${{ matrix.java }}
            cache: 'sbt'

        - name: Scalafmt lint
          run: sbt 'scalafmtCheckAll'

        - name: Scalafix checks
          run: sbt 'scalafixAll --check'

        - name: Scalatest
          run: sbt test

  release:
    name: Release
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: semantic release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}